### ISSUE TITLE
Not converting protocol correctly when input differs from the allowed.

### ISSUE THREAD

**Issue by Daniellunsc** [bauripalash/fossurl#11]
When i type something like adasdasd://google.com, it doenst remove the invalid protocol and append the allowed one("http://", "https://", "ftp://").

An example:
![image](https://user-images.githubusercontent.com/16923217/45853783-91a4d480-bd1d-11e8-884a-e91de7a46903.png)

![image](https://user-images.githubusercontent.com/16923217/45853789-9bc6d300-bd1d-11e8-9865-99f342967d55.png)

The url after:
![image](https://user-images.githubusercontent.com/16923217/45853796-a1241d80-bd1d-11e8-8a47-e3814df71a5b.png)

**Comment by bauripalash** [comment]
I found the problem. but couldn't find a way to fix that without messing the whole system. Will try to fix that soon.

**Comment by agiltriono** [comment]
maybe this is the problem 
"http://"+url;
i only edit that line into url the if statement only return true event if false it still append to json with that value

so user can see notice the url is invalid or not

**Comment by bauripalash** [comment]
@Daniellunsc  The issue is resolved now! Checkout our new design with new improved code : https://fossurl.ml

**Comment by Daniellunsc** [comment]
Nice! It was fun to contribute.

Enviado do meu iPhone

Em 12 de dez de 2018, à(s) 06:21, Palash Bauri <notifications@github.com> escreveu:
