### ISSUE TITLE
Stored XSS security bug

### ISSUE THREAD

**Issue by p410n3** [bauripalash/fossurl#12]
Steps to reproduce:

Use the chrome console to remove the **clientside**  URL check:

![JS](https://i.imgur.com/vEcIIZh.png)

Enter malicous "javascript:" URL

![XSS](https://i.imgur.com/ZPnrJGq.png)

Send link around to phish people using defacements or CSRF to other sites.

![Final](https://i.imgur.com/r9ewj2b.png)

**Comment by p410n3** [comment]
Regarding a fix, that would obvisouly require a backend. Referncing this. https://github.com/bauripalash/fossurl/issues/2#issuecomment-440883946

Ill say to just focus on the re code. 

Good luck

**Comment by AntonyGarand** [comment]
I disagree with the parent comment, it would be pretty simple to fix this on the client-side.
Instead of arbitrarily redirecting to the given URL, you could validate that the url starts with `http://` or `https://`, and not redirect if it doesn't match.

**Comment by bauripalash** [comment]
@AntonyGarand In the new version I'm using regular expression to validate URLs before creating new short urls

**Comment by p410n3** [comment]
> @AntonyGarand In the new version I'm using regular expression to validate URLs before creating new short urls

He means to validate before redirecting. Not only when creating the link, That's a solution, I haven't thought of that.

That still leaves the JS in the JSONStore but at least it wint affect the users clicking the link.

Thanks for the input @AntonyGarand

**Comment by bauripalash** [comment]
@p410n3 @AntonyGarand I'm not sure about efficiency but I added regex to verify the URL before redirecting https://github.com/bauripalash/fossurl/commit/5537e32384876e10c48edda603cc436876d78be8

**Comment by bauripalash** [comment]
No Update! Closing It!

**Comment by AntonyGarand** [comment]
Your regex works, but is a bit overkill.
You could ensure the link starts with `http(s)?` and it should be fine

**Comment by bauripalash** [comment]
@AntonyGarand At first I was thinking same , but then i thought what if someone shortens a url with other protocols such as ftp , whatsapp etc.. that's why i used regex..

**Comment by AntonyGarand** [comment]
If you want to support every protocol other than JS, you can blacklist links starting with `javascript` instead

**Comment by bauripalash** [comment]
@AntonyGarand Noted 🙂
