### ISSUE TITLE
Feat: Add Link Error Checking

### ISSUE THREAD

**Issue by dica53** [bauripalash/fossurl#13]
For example, if I did not enter a link, show an error or toast when I try to generate link. I was able to generate a link without entering anything. 

I was also able to enter stuff like `asdasd` and `.` and still get a link.

**Comment by bauripalash** [comment]
Feel Free to send pr if you can ❤

**Comment by bauripalash** [comment]
Similar to https://github.com/bauripalash/fossurl/issues/11

**Comment by bauripalash** [comment]
@jonathanzhang53 The issue is resolved now! Checkout our new design with new improved code : https://fossurl.ml
