### ISSUE TITLE
[Internationalization]  Add Translations

### ISSUE THREAD

**Issue by bauripalash** [bauripalash/fossurl#17]
### Suggestion
Currently FossURL is only available in English. It would be useful if it had multiple language support but without effecting the performance! 

#### Some Languages Would Be:

* [ ] **Bengali**
* [ ] **Chinese**
* [ ] **Hindi**
* [ ] **Spanish**
* [ ] **French**
etc.

**Comment by jocelo** [comment]
hey!

I can help you with the Spanish (latin) translation... any particular way on how to implement it ?

**Comment by bauripalash** [comment]
@jocelo , Actually , it's kinda TODO Thing , no plans or idea how I'm gonna implement the system

**Comment by jocelo** [comment]
ok
