### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ghost** [bauripalash/fossurl#19]
Not Working because jsonstore.io is having some trouble for many days 
can you please rewrite the script for using with other such free json hosts
like [jsonbox.io](https://jsonbox.io/) ?

**Comment by bauripalash** [comment]
@aliglelo you're right! jsonstore isn't returning any data. jsonbox.io seems nice. do you know if they have any usage quota ?

**Comment by bauripalash** [comment]
@aliglelo i have done some work with jsonbox in the #dev branch.

**Comment by ghost** [comment]
> @aliglelo you're right! jsonstore isn't returning any data. jsonbox.io seems nice. do you know if they have any usage quota ?

Here is the limitations for jsonbox.io:
https://github.com/vasanthv/jsonbox#limitations

**Comment by ghost** [comment]
> @aliglelo i have done some work with jsonbox in the #dev branch.

I checked it but it doesn't seems to work bro

**Comment by bauripalash** [comment]
@aliglelo I haven't deployed the branch to production yet. I need to do some more optimizations and testing.

**Comment by ghost** [comment]
> @aliglelo I haven't deployed the branch to production yet. I need to do some more optimizations and testing.
I have tested it on my local server but it didn't worked there
i hope you will fix it soon
Best of luck
