### ISSUE TITLE
JSONstore allows anyone to just purge the list using DELETE requests.

### ISSUE THREAD

**Issue by p410n3** [bauripalash/fossurl#2]
Do a backup before somebody deletes it!

**Comment by bauripalash** [comment]
I encourage people to host it themselves and use their own jsonstore endpoint.

**Comment by p410n3** [comment]
Which still allows everyone to just read the URL out of the index.js and mess with the JSON however he wants. JSONstore is not secure to use that way. At least proxy the request using PHP / node / perl or a damn bash script. The JSONstore URL is basically a secret. Dont expose it.

You can rely on another service or make your own if you realy wanna keep it Client side only, but security wise its just not good right now.

**Comment by bauripalash** [comment]
@p410n3 Any Suggestions of another service ??

**Comment by p410n3** [comment]
now.sh or heroku

**Comment by bauripalash** [comment]
i tried now.sh but i can't install their cli as i have 32bit ubuntu linux.
and in heroku , a plan has to be bought unless wait for 10 seconds

**Comment by p410n3** [comment]
I still believe you should try to find a Database that can not be deleted by literally everyone. Something that only allows you to add new data is fine. 

Not being able to see other ppls data is a plus, but just being able to delete the whole thing in  one second kinda sucks dont you think?

**Comment by bauripalash** [comment]
@p410n3 I'm planning to rewrite the whole thing in NodeJS and with MySQL Database, as soon as my **school exam** ends and also the **Google Code-in** (In which I'm Participating)
