### ISSUE TITLE
fossurl.ml Down

### ISSUE THREAD

**Issue by chrisjbawden** [bauripalash/fossurl#27]
Unable to reach - fossurl.ml.

**Comment by bauripalash** [comment]
Yes. The domain name is gone 🤷‍♂️.
The new address is https://palashbauri.in/fossurl/

**Comment by chrisjbawden** [comment]
Ahhhh. You might need to update you readme to amend the URL.

<img width="698" alt="Screen Shot 2020-10-13 at 3 51 50 pm" src="https://user-images.githubusercontent.com/35166625/95820835-33b41100-0d6c-11eb-8010-e70a534aec5d.png">

**Comment by bauripalash** [comment]
Done
