### ISSUE TITLE
jsonbox will soon be shut down on May 31st, 2021

### ISSUE THREAD

**Issue by eallion** [bauripalash/fossurl#28]
The notice from their website <https://jsonbox.io/>

> Note: Jsonbox.io cloud instance will soon be shut down on May 31st, 2021 due to lack of maintenance time. The Jsonbox.io's source code will continue to be open-sourced in Github.

> FYI, you can create your own Jsonbox.io instance for free using Heroku & MongoDB Cloud. Go for it if you love Jsonbox.io :)

**Comment by bauripalash** [comment]
any alternative?

**Comment by eallion** [comment]
Sorry, I have no idea.
I heard about this repo and jsonbox 2 days ago.

**Comment by AnthonyArutyunov** [comment]
the closest thing that I found to jsonbox.io is jsonbase.com. Though I'm not sure if its format will work for your api.

**Comment by bauripalash** [comment]
I think I'll have to archive and suspend this project

**Comment by AnthonyArutyunov** [comment]
I forked jsonbox.io and created http://jsonconnect.com/. It works and I already tried it with your link shortener. I'm still working on the UI, but the website is completely functional.

**Comment by bauripalash** [comment]
I am planning to shut down and archive this project

**Comment by AnthonyArutyunov** [comment]
👍
