### ISSUE TITLE
Demo Fails To Do Anything

### ISSUE THREAD

**Issue by jlpoolen** [bauripalash/fossurl#5]
I visited the " >Working Demo<" in the readme file posted on this project, the link resolves to

     https://fossurl.palash.tk/

and entered "http://www.google.com" in the box and pushed the button "Short Me" and nothing happens, it is as if the button was nonfunctional.

**Comment by bauripalash** [comment]
I think it worked. Have you read the instructions below the button?

Whenever you shorten a url (enter an url in box and push the Short Me button)  , short url is automatically copied to your clipboard

**Comment by jlpoolen** [comment]
No, I did not read the instructions below the button.
I tried entering "http://www.google.com" and then found in my clipboard
"https://fossurl.palash.tk/#gc3foi"

Thank you. I'm closing this ticket.

**Comment by bauripalash** [comment]
Glad To Hear it is working fine!
