### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Batarian711** [bauripalash/fossurl#9]
Hello. I want to contribute voluntarily to the project. I designed this logo for you. What do you think?

![fossurl](https://user-images.githubusercontent.com/41051393/42995301-2d55526e-8c19-11e8-8e0a-539435b77d92.jpg)

**Comment by bauripalash** [comment]
I appreciate your hard work!
But your logo design doesn't symbolise what our program does.
A user should be able identify a programs work by it's logo!

**Comment by Batarian711** [comment]
Tell me if you want to design something. I can design.

**Comment by bauripalash** [comment]
I don't have a specific design in mind.

But i have some words in mind,
* Short
* New thing which was never imagined
* URL
* Link
etc.

I think it would be great if helps to people understand what it actually do.

**Comment by bauripalash** [comment]
@Batarian711 ??

**Comment by Batarian711** [comment]
I wanted to tell you about my design. Foss represents the word bone. Url kelimesini is round. The middle strip represents the http area. What dou you think? 

![fossurl](https://user-images.githubusercontent.com/41051393/43035661-917185cc-8cfc-11e8-9ca8-fee69627e46c.jpg)

**Comment by bauripalash** [comment]
FossURL , where *foss* is acronym for *Free and Open Source Software* , but how Does a *bone* came here 😟 ?

**Comment by Batarian711** [comment]
I did not know how to reflect the fossil otherwise. If you like it, I'il send you files.

**Comment by bauripalash** [comment]
It's not about **fossil**.
I'm talking about **FOSS**
Which is **Free and Open Source Software**
